### ISSUE TITLE
首页的这个alink hover的效果不好

### ISSUE THREAD

**Issue by astaxie** [gocn/feedback#1]
![image](https://user-images.githubusercontent.com/233907/142719786-adca6c58-94be-4ac9-a1f9-aafc8f02231e.png)

这个框是不是可以大一点

老的样式：

![image](https://user-images.githubusercontent.com/233907/142719799-cbdd20a5-03e1-4497-8416-8afdc8206655.png)

**Comment by luyang950** [comment]
优化了一下卡片样式：
<img width="1259" alt="首页卡片" src="https://user-images.githubusercontent.com/14934210/143765766-7cb614cc-c83e-41ff-a993-3d79845bb562.png">

首页整体样式可能需要一次大改，抽空一起讨论一个方案，暂不作小修补。
