### ISSUE TITLE
点击用户提示出错

### ISSUE THREAD

**Issue by astaxie** [gocn/feedback#3]
https://forum.gocn.vip/profile/%E6%B8%94%E5%A4%AB%E5%AD%90

![image](https://user-images.githubusercontent.com/233907/142720008-1c3bcd9a-48e9-4244-9adb-b9047bf72226.png)

**Comment by luyang950** [comment]
用户未迁移至新系统导致，如果是未迁移用户则不提供此页面的链接，且在此页面给提示。
