### ISSUE TITLE
编辑器插入图片出错

### ISSUE THREAD

**Issue by astaxie** [gocn/feedback#5]
1. 提示应该更加准确

![image](https://user-images.githubusercontent.com/233907/142720249-4bee90d5-94cd-4e98-bf5f-87f416b00e78.png)

**Comment by luyang950** [comment]
已提供图片过大时的用户提示：
<img width="1160" alt="图片过大" src="https://user-images.githubusercontent.com/14934210/143762935-da12fffb-6daf-404d-9296-11cb027dd9a7.png">
