### ISSUE TITLE
评论失败

### ISSUE THREAD

**Issue by astaxie** [gocn/feedback#6]
评论太长的话，是不是提前有一个提示？

![image](https://user-images.githubusercontent.com/233907/142720295-d258d6dd-f90d-40a9-ae66-77588419aed9.png)

**Comment by luyang950** [comment]
评论过长时会disable评论按钮并修改文案:
<img width="990" alt="评论过长" src="https://user-images.githubusercontent.com/14934210/143744830-e9f5523b-50c5-46fe-a6a7-783fe53991d3.png">
